[package]
authors = [
    "sword-smith <thor@neptune.cash>",
    "Alan Szepieniec <alan@neptune.cash>",
    "Philip Munksgaard <philip@munksgaard.me>",
]
edition = "2021"
name = "neptune-core"
version = "0.1.0"
default-run = "neptune-core"

[dev-dependencies.cargo-husky]
default-features = false                                           # Disable features which are enabled by default
features = ["precommit-hook", "run-cargo-clippy", "run-cargo-fmt"]
version = "1"

[dependencies]
twenty-first = { git = "ssh://git@neptune.builders:2222/core-team/twenty-first.git", rev = "06203486b6740cb0ca14bd1e7fdd2ec3ee0e2922" }
mutator-set-tf = { git = "ssh://git@neptune.builders:2222/core-team/mutator-set-tf.git", rev = "3c103f38390496ae89eeeebd4518a44da188e328" }
# twenty-first = { path = "../twenty-first/twenty-first" }
# mutator-set-tf = { path = "../mutator-set-tf" }
anyhow = "1" # Error trait and generalized error handling
bincode = "1"
bytes = "1"
chrono = "0.4"
clap = { version = "3", features = ["derive"] } # command-line parsing
directories = "4"
futures = "0.3"
memmap2 = "0"
num-bigint = { version = "0.4", features = ["serde"] }
num-traits = "0.2"
rand = "0.8"
rusty-leveldb = "1"
secp256k1 = { version = "0", features = [
    "rand-std",
    "serde",
    "global-context",
    "bitcoin_hashes",
] }
serde = { version = "1", features = ["derive"] }
serde_derive = "1"
serde_json = "1"
tokio = { version = "1", features = ["full", "tracing"] }
tokio-serde = { version = "0.8", features = ["bincode", "json"] }
tokio-util = { version = "0.7", features = ["codec"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = [
    "std",
    "env-filter",
    "time",
    "fmt",
] }
tracing-test = "0"
tarpc = { version = "0.30", features = ["tokio1", "serde-transport", "tcp"] }
priority-queue = "1.2"
get-size = { version = "^0.1", features = ["derive"] }
num-rational = "0.4"

[dev-dependencies]
pin-project-lite = "0.2"
tokio-test = "0.4"
