[package]
authors = ["Triton Software"]
edition = "2021"
name = "neptune-core"
version = "0.7.2"
default-run = "neptune-core"
publish = false

[dev-dependencies.cargo-husky]
default-features = false                                           # Disable features which are enabled by default
features = ["precommit-hook", "run-cargo-clippy", "run-cargo-fmt"]
version = "1"

[dependencies]
aead = "0.5.2"
aes-gcm = "0.10.1"
bech32 = "0.9.1"
twenty-first = "0.24.0"
# twenty-first = { path = "../twenty-first/twenty-first" }
# mutator-set-tf = { git = "ssh://git@neptune.builders:2222/core-team/mutator-set-tf.git" }
mutator-set-tf = { path = "../mutator-set-tf" }
anyhow = "1"
bincode = "1"
bytes = "1"
chrono = "0.4"
clap = { version = "4", features = ["derive"] }
directories = "4"
futures = "0.3"
itertools = "0.10"
memmap2 = "0"
num-bigint = { version = "0.4", features = ["serde"] }
num-traits = "0.2"
rand = "0.8"
rusty-leveldb = "1"
serde = { version = "1", features = ["derive"] }
serde_derive = "1"
serde_json = "1"
tarpc = { version = "0.30", features = ["tokio1", "serde-transport", "tcp"] }
tokio = { version = "1", features = ["full", "tracing"] }
tokio-serde = { version = "0.8", features = ["bincode", "json"] }
tokio-util = { version = "0.7", features = ["codec"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = [
    "std",
    "env-filter",
    "time",
    "fmt",
] }
tracing-test = "0"
triton-vm = {path = "../triton-vm/triton-vm"}
triton-opcodes = {path = "../triton-vm/triton-opcodes"}
priority-queue = "1.2"
get-size = { version = "^0.1", features = ["derive"] }
num-rational = "0.4"
bytesize = "1.1"
tui = "0.19"
crossterm = "0.25"
unicode-width = "0.1.5"
strum = "0.24"
strum_macros = "0.24"

[dev-dependencies]
pin-project-lite = "0.2"
tokio-test = "0.4"
