[package]
name = "neptune-core"
version = "0.1.0"
authors = ["sword-smith <thv@neptune.cash>", "Alan Szepieniec <as@neptune.cash>"]
edition = "2018"

[dependencies]
anyhow = "1.0" # Error trait and generalized error handling
chrono = "0.4"
structopt = { version = "0.3", features = [ "paw" ] } # Command-line argument parsing
paw = "1.0" # Command-line argument parsing
log = { version = "0.4", features = [ "std" ] }
