[package]
name = "mutator-set-tf"
version = "0.1.0"
authors = ["Triton Software AG"]
edition = "2021"

[dev-dependencies]
proptest = "1.0"

[dev-dependencies.criterion]
version = "0.3"
features = ["html_reports"]

[dev-dependencies.cargo-husky]
version = "1"
default-features = false
features = ["precommit-hook", "run-cargo-clippy", "run-cargo-fmt"]

[dependencies]
twenty-first = { git = "ssh://git@neptune.builders:2222/core-team/twenty-first.git", rev = "95a385cec47706edc66fcddf79780b5511699844" }
blake3 = "1"
itertools = "0"
rand = "0"
rand_core = "0"
rayon = "1"
rusty-leveldb = "1"
serde = { version = "1", features = ["derive"] }
serde-big-array = "0"
serde_derive = "1"
serde_json = "1"

[profile.dev]
opt-level = 0
debug = true
split-debuginfo = '...'
debug-assertions = true
overflow-checks = true
lto = false
panic = 'unwind'
incremental = true
codegen-units = 256
rpath = false

[profile.release]
opt-level = 3
debug = false
split-debuginfo = '...'
debug-assertions = false
overflow-checks = false
lto = false
panic = 'unwind'
incremental = false
codegen-units = 16
rpath = false

[profile.test]
opt-level = 0
debug = true
split-debuginfo = '...'
debug-assertions = true
overflow-checks = true
lto = false
incremental = true
codegen-units = 256
rpath = false

[profile.bench]
opt-level = 3
debug = false
split-debuginfo = '...'
debug-assertions = false
overflow-checks = false
lto = false
incremental = false
codegen-units = 16
rpath = false
