[package]
authors = ["sword-smith <thv@neptune.cash>", "Alan Szepieniec <as@neptune.cash>"]
edition = "2018"
name = "neptune-core"
version = "0.1.0"

[dev-dependencies.cargo-husky]
default-features = false # Disable features which are enabled by default
features = ["precommit-hook", "run-cargo-clippy", "run-cargo-fmt"]
version = "1"

[dependencies]
anyhow = "1.0" # Error trait and generalized error handling
bytes = "1.1"
chrono = "0.4"
futures = "0.3.17"
paw = "1.0" # Command-line argument parsing
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0"
structopt = { version = "0.3", features = [ "paw" ] } # Command-line argument parsing
tokio = { version = "1", features = ["full"] }
tokio-serde = { version = "0.8.0", features = ["bincode"] }
tokio-util = { version = "0.6.8", features = ["codec"] }
tracing = "0.1.5"
tracing-subscriber = "0.2.20"

[dev-dependencies]
pin-project-lite = "0.2.4"
tokio-test = "0.4.2"
