[package]
name = "rust-template-project"
version = "0.1.0"
authors = ["Philip Munksgaard <philip@munksgaard.me>"]
edition = "2018"

[dependencies]
anyhow = "1.0" # Error trait and generalized error handling
structopt = { version = "0.3", features = [ "paw" ] } # Command-line argument parsing
paw = "1.0" # Command-line argument parsing
